public enum EventID
{
	ON_RING_STACK_NUMBER_CHANGE,
	ON_COMPLETE_LEVEL,
	ON_INIT_LEVEL,
	ON_LOADED_REWARDED_AD,
	ON_FAILED_LOAD_REWARDED_AD,
	ON_CHANGED_UNDO_TIME,
	ON_GO_NEXT_LEVEL_DEBUG,
	ON_GO_PREVIOUS_LEVEL_DEBUG
}